apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-ladtocqn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-ladtocqn:c6d7ff1e21569ea37172488ecad11acf349d2703@sha256:889c8836fb8dcc6a769c71db3e644907b2edb2325db5424c15abeb5c0300f7f7
          name: container-image
